{
  "training": {
    "n_eval_episodes": 10
  },
  "bc": {
    "epochs": 20,
    "batch_size": 256,
    "learning_rate": 0.001,
    "weight_decay": 0,
    "aux_weight": 0.9,
    "action_reweight_on_holding_target": 2.0,
    "min_sampling_proba": 0.1
  }
}
