{
  "training": {
    "n_eval_episodes": 20,
    "eval_max_steps": 256
  },
  "bc": {
    "epochs": 5,
    "batch_size": 256,
    "learning_rate": 0.0003,
    "weight_decay": 0.0,
    "aux_weight": 2.0,
    "action_reweight_on_holding_target": 2.0,
    "min_sampling_proba": 0.1,
    "sampling_episode_budget_per_task": 1000
  }
}
