{
  "training": {
    "n_envs": 1,
    "total_timesteps": 10000,
    "save_freq": 1000,
    "eval_freq": 1000,
    "n_eval_episodes": 4
  },
  "ppo": {
    "batch_size": 128
  },
  "bc": {
    "epochs": 1
  }
}
