{
  "action_dim": 7,
  "image_embedding_dim": 256,
  "mission_embedding_dim": 128,
  "mission_hidden_dim": 256,
  "attention": true,
  "features_dim": 512,
  "recurrent_hidden_dim": 512,
  "tile_vocab_sizes": {
    "object": 16,
    "color": 16,
    "state": 8
  }
}
