{
  "action_dim": 7,
  "image_embedding_dim": 96,
  "mission_embedding_dim": 32,
  "mission_hidden_dim": 64,
  "attention": false,
  "features_dim": 128,
  "recurrent_hidden_dim": 128,
  "tile_vocab_sizes": {
    "object": 16,
    "color": 16,
    "state": 8
  }
}
